kind: pipeline
type: kubernetes
name: privateGPT
steps:
- name: build
  image: docker:dind
  volumes:
  - name: docker_sock
    path: /var/run
  commands:
  - docker build . -t 10.8.0.14:32000/privategpt:latest -t 10.8.0.14:32000/privategpt:${DRONE_COMMIT_SHA:0:7}
  - docker push 10.8.0.14:32000/privategpt:${DRONE_COMMIT_SHA:0:7}

- name: deliver
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: k8s_server
    kubernetes_cert:
      from_secret: k8s_cert
    kubernetes_token:
      from_secret: k8s_token
  commands:
    - kubectl apply -f deployment.yml
    - kubectl set image -n privateGPT deployment.v1.apps/privateGPT-app privateGPT-app=10.8.0.14:32000/privategpt:${DRONE_COMMIT_SHA:0:7}

volumes:
  - name: docker_sock
    host:
      path: /var/run