apiVersion: v1
kind: Service
metadata:
  name: bryllup-service
  namespace: bryllup
spec:
  selector:
    name: bryllup-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bryllup-app
  namespace: bryllup
spec:
  selector:
    matchLabels:
      name: bryllup-app
  replicas: 3
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        name: bryllup-app
    spec:
      containers:
      - name: bryllup-app
        image: 10.8.0.14:32000/bryllup
        imagePullPolicy: Always
        ports:
        - containerPort: 80